"""Reviewer Agent: Formats raw Markdown into Telegram HTML for pristine visual aesthetics."""
import re
import html
import logging

logger = logging.getLogger(__name__)


class ReviewerAgent:
    """Agent 3: Sanitizes response output into beautiful Telegram HTML prose."""

    @staticmethod
    def strip_markdown(text: str) -> str:
        """Alias for format_for_telegram_html."""
        return ReviewerAgent.format_for_telegram_html(text)

    @staticmethod
    def format_for_telegram_html(text: str) -> str:
        """Transforms raw Markdown into pristine, beautiful Telegram HTML formatting."""
        if not text:
            return ""

        # 1. Save code blocks (```python ... ```) -> <pre><code>...</code></pre>
        code_blocks = []
        def save_code_block(match):
            code_content = html.escape(match.group(2).strip())
            code_blocks.append(f"<pre><code>{code_content}</code></pre>")
            return f"___CODE_BLOCK_{len(code_blocks)-1}___"

        text = re.sub(r"```([\w]*)\n?(.*?)```", save_code_block, text, flags=re.DOTALL)

        # 2. Save inline code (`code`)
        inline_codes = []
        def save_inline_code(match):
            code_content = html.escape(match.group(1))
            inline_codes.append(f"<code>{code_content}</code>")
            return f"___INLINE_CODE_{len(inline_codes)-1}___"

        text = re.sub(r"`([^`\n]+)`", save_inline_code, text)

        # 3. Escape HTML special characters for remaining prose
        text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

        # Restore code blocks and inline code placeholders
        for idx, block in enumerate(code_blocks):
            text = text.replace(f"___CODE_BLOCK_{idx}___", block)
        for idx, code in enumerate(inline_codes):
            text = text.replace(f"___INLINE_CODE_{idx}___", code)

        # 4. Remove horizontal dividers (--- or ***)
        text = re.sub(r"^\s*[\-\*_]{3,}\s*$", "", text, flags=re.MULTILINE)

        # 5. Format unordered list bullets FIRST (* item or - item -> • item)
        text = re.sub(r"^\s*[\*\-\+]\s+", "• ", text, flags=re.MULTILINE)

        # 6. Convert headers (### Header -> <b>📘 Header</b>)
        def format_header(match):
            title = match.group(2).strip()
            if any(ord(char) > 0x2000 for char in title[:2]):
                return f"\n<b>{title}</b>\n"
            return f"\n<b>📘 {title}</b>\n"

        text = re.sub(r"^(#{1,6})\s+(.+)$", format_header, text, flags=re.MULTILINE)

        # 7. Convert bold (**bold** -> <b>bold</b>)
        text = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", text)

        # 8. Convert italics (*italic* -> <i>italic</i>)
        text = re.sub(r"(?<!\*)\*([^\*\n]+)\*(?!\*)", r"<i>\1</i>", text)
        text = re.sub(r"(?<!_)_([^_\n]+)_(?!_)", r"<i>\1</i>", text)

        # 9. Convert links ([title](url) -> <a href="url">title</a>)
        text = re.sub(r"\[([^\]]+)\]\((https?://[^)]+)\)", r'<a href="\2">\1</a>', text)

        # 10. Convert blockquotes (> quote -> <i>💬 quote</i>)
        text = re.sub(r"^\s*&gt;\s*(.+)$", r"<i>💬 \1</i>", text, flags=re.MULTILINE)

        # 11. Clean up excessive consecutive blank lines
        text = re.sub(r"\n{3,}", "\n\n", text)

        return text.strip()

    def validate_and_sanitize(self, text: str, strict: bool = True) -> str:
        """Sanitizes text and verifies formatting boundaries."""
        if not text:
            return "No content was generated by the cognitive engine."
        return self.format_for_telegram_html(text)
